[build]
  publish = "."
  command = "pip install -r requirements-deploy.txt"

[build.environment]
  PYTHON_VERSION = "3.9"

# Redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/main/webhook"
  status = 200

[[redirects]]
  from = "/facebook-setup"
  to = "/.netlify/functions/main/facebook-setup"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://connect.facebook.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self' https://graph.facebook.com;"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Context environments
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Custom error page
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Dev server
[dev]
  command = "python main.py"
  port = 5000
  targetPort = 5000
  autoLaunch = true

# Functions
[functions]
  directory = "netlify/functions"
