[build]
  # Build configuration for Netlify
  publish = "."
  command = "pip install -r requirements-deploy.txt"

[build.environment]
  # Python version for functions
  PYTHON_VERSION = "3.11"

# Functions configuration for Flask app  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/main/webhook"
  status = 200

[[redirects]]
  from = "/facebook-setup"
  to = "/.netlify/functions/main/facebook-setup"
  status = 200

# Serve static files
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Fallback for all other routes to Flask app
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main/:splat"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://connect.facebook.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self' https://graph.facebook.com;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS and JS files
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set these in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Form handling (if needed for contact forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Custom error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404

# Edge functions configuration (for advanced features)
[edge_functions]
  path = "/api/*"

# Plugin configuration for optimization
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Development settings
[dev]
  command = "python main.py"
  port = 5000
  targetPort = 5000
  autoLaunch = true

# Function configuration for serverless deployment
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Asset optimization
[build.processing.images]
  compress = true
